import com.github.spotbugs.snom.Effort
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

buildscript {
	ext {
		springVersion    = '3.4.3'
		mapStructVersion = '1.6.3'
	}
}

plugins {
	id 'java'
	id 'jvm-test-suite'
	id 'checkstyle'
	id 'jacoco'
	id 'org.springframework.boot' version "$springVersion"
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.17.0'
	id 'com.github.spotbugs' version '6.4.8'
}

group = 'com.panopticode'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	// MapStruct
	compileOnly "org.mapstruct:mapstruct:$mapStructVersion"
	annotationProcessor "org.mapstruct:mapstruct-processor:$mapStructVersion"

	// Logging
	implementation 'org.slf4j:slf4j-api:2.0.17'
	implementation 'ch.qos.logback:logback-classic'
	implementation 'ch.qos.logback:logback-core'
	implementation 'ch.qos.logback.access:logback-access-common:2.0.6'

	// Spring
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Additional dependencies for OpenAPI
	implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
	implementation 'org.springdoc:springdoc-openapi-ui:1.8.0'

	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Checks
	spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.13.0'

	// Custom checks
	checkstyle project(':custom-checks')
}

ext['junit-jupiter.version'] = '5.12.0'

testing {
	suites {
		test {
			useJUnitJupiter()

			dependencies {
				implementation project(':test-common')
				implementation platform('org.junit:junit-bom:5.12.0')
				implementation 'org.assertj:assertj-core:3.27.3'
				implementation 'org.mockito:mockito-core:5.15.2'
				implementation 'org.mockito:mockito-junit-jupiter:5.15.2'

				runtimeOnly 'org.junit.platform:junit-platform-launcher'
			}

			sources {
				java {
					srcDirs = ['src/test/unit/java']
				}
				resources {
					srcDirs = ['src/test/resources']
				}
			}
		}
	}
}

// Idk why the jvm-test-suite seems to ungroup the checkstyle tasks
tasks.withType(Checkstyle.class).configureEach {
	group = 'Verification'
}

test {
	jacoco {
		classDumpDir = layout.buildDirectory.dir('jacoco/unit/classpathdumps').get().asFile
	}

	finalizedBy jacocoTestReport
}

jacoco {
	toolVersion = '0.8.11'
}

jacocoTestReport {
	dependsOn test
	sourceSets sourceSets.main
	executionData fileTree(project.rootDir.absolutePath).include("build/jacoco/*.exec")

	reports {
		html.required = true
	}

	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
					"com/panopticode/openapi/**"
			])
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.85
			}
		}

		rule {
			enabled = false
			element = 'CLASS'
			includes = ['com.panopticode.ingest.*']

			limit {
				counter = 'LINE'
				value = 'TOTALCOUNT'
				maximum = 0.3
			}
		}
	}
}

bootRun {
	systemProperties = System.properties
}

checkstyle {
	toolVersion = '10.14.2'
}

//import com.github.spotbugs.snom.Confidence
spotbugs {
	toolVersion = '4.8.3'
	ignoreFailures = false
	showStackTraces = true
	showProgress = true
	effort = Effort.MAX
//	reportLevel = Confidence.DEFAULT
//	visitors = listOf("FindSqlInjection", "SwitchFallthrough")
//	omitVisitors = listOf("FindNonShortCircuit")
//	reportsDir = file("$buildDir/spotbugs")
//	includeFilter = file("include.xml")
	excludeFilter = file("$projectDir/config/spotbugs/exclude.xml")
//	baselineFile = file("baseline.xml")
//	onlyAnalyze = listOf("com.foobar.MyClass", "com.foobar.mypkg.*")
//	maxHeapSize = "1g"
//	extraArgs = listOf("-nested:false")
//	jvmArgs = listOf("-Duser.language=ja")
}

tasks.spotbugsMain {
	reports.create("html") {
		required = true
//		outputLocation = file("$buildDir/reports/spotbugs.html")
		setStylesheet("fancy-hist.xsl")
	}
}

tasks.register('bundleApiSpecs', Exec) {
	description = 'Bundle all the api specs into one file'
	group = 'OpenAPI Tools'

	commandLine 'docker', 'run',
			'--rm',
			'-v', "$projectDir/api:/spec",
			'redocly/cli:2.12.6',
			'bundle',
			'openapi.yaml',
			'-o', 'bundled.yaml'

	outputs.file(layout.buildDirectory.file('openapi/openapi.yaml'))

	doLast {
		println "Copying bundled API specs to build directory..."

		copy {
			from layout.projectDirectory.file('api/bundled.yaml')
			into layout.buildDirectory.dir('openapi')

			rename 'bundled', 'openapi'
		}

		delete "${rootDir}/api/bundled.yaml"
	}
}

// This task is an internal utility and it's not polished
// it reads the specs at api/openapi.yaml and create the documents
// inside api/ingest/. The openapi.yaml rooted there needs to be
// moved where the original was and all the $refs fixed.
tasks.register('splitApiSpecs', Exec) {
	description = 'Split the full API spec in the openapi.yaml'

	commandLine 'docker', 'run',
			'--rm',
			'-v', "$projectDir/api:/spec",
			'redocly/cli:2.12.6',
			'split',
			'openapi.yaml',
			'--outDir', './ingest'
}

openApiValidate {
	inputSpec.set("$projectDir/api/openapi.yaml")
	recommend.set(true)
}

tasks.named('openApiValidate') {
	dependsOn(bundleApiSpecs)
}

openApiGenerate {
	verbose.set(true)
	generatorName.set('spring')
	outputDir.set("$projectDir")
	inputSpecRootDirectory.set("$projectDir/build/openapi")
	inputSpec.set("$projectDir/build/openapi/openapi.yaml")
	invokerPackage.set('com.panopticode.openapi')
	apiPackage.set('com.panopticode.openapi.api')
	modelPackage.set('com.panopticode.openapi.model')
	configOptions = [
			useSpringBoot3      : 'true',
			delegatePattern     : 'true',
			useTags             : 'true',
			library             : 'spring-boot',
			requestMappingMode  : 'controller',
			booleanGetterPrefix : 'is',
			configPackage       : 'com.panopticode.openapi.configuration',
			sourceFolder        : 'src/main/java/generated',
			title               : 'ingest-microservice_OpenAPI',
	]
}

tasks.named('openApiGenerate') {
	dependsOn(bundleApiSpecs)
}

tasks.register('generateDocs', GenerateTask) {
	description = 'Generate html documentation of the ingest-microservice public API using the OpenAPI engine.'
	group = 'OpenAPI Tools'

	dependsOn bundleApiSpecs
	generatorName.set('html2')
	outputDir.set("$projectDir/docs")
	inputSpec.set("$projectDir/build/openapi/openapi.yaml")
	configOptions = [
			appName        : 'ingest-microservice',
			appDescription : 'A template code base for a java Spring Boot micro-service, with database versioning, a RESTful API defined and documented using OpenAPI and a compelling test suite.',
			artifactVersion: '1.0.0',
			infoEmail      : 'sink@etlgr.com',
			infoUrl        : 'https://www.wikipedia.org',
			licenseInfo    : 'GPL v3',
			licenseUrl     : 'https://www.gnu.org/licenses/gpl-3.0.en.html',
	]
}

tasks.register('printSourceSetInformation') {
	description = 'Print information about the source sets in this project and their classpaths.'
	group = 'Help'

	doLast{
		sourceSets.each { srcSet ->
			println "["+srcSet.name+"]"
			print "-->Source directories: "+srcSet.allJava.srcDirs+"\n"
			print "-->Output directories: "+srcSet.output.classesDirs.files+"\n"
			print "-->Compile classpath:\n"
			srcSet.compileClasspath.files.each {
				print "  "+it.path+"\n"
			}
			println ""
		}
	}
}
