services:
  webapp:
    image: 'ingest-microservice-webapp:rc1'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'ingest-microservice-webapp'
    ports:
      - '8081:8080'
    expose:
      - '8000'
