server.servlet.context-path=/api/v1/ingest

spring.jackson.date-format=com.panopticode.openapi.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Enable to debug application at runtime
#logging.level.root=TRACE