openapi: 3.0.3
info:
  title: ingest-microservice
  description: >-
    ingest-microservice

    This is the public API to interact with your webapp, based on the OpenAPI
    3.0 specification.
  termsOfService: https://twitter.com/en/tos
  contact:
    name: API Support
    url: https://www.begambleaware.org/
    email: sink@etlgr.com
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

servers:
  - url: http://localhost:{port}/api/v1/ingest
    description: Local development container
    variables:
      port:
        enum:
          - '8080'
        default: '8080'
  - url: https://raspberrypi.tigon-court.ts.net/api/v1/ingest
    description: Production server

tags:
  - name: ingest
    description: Write API for data
    externalDocs:
      description: Find out more
      url: https://neal.fun

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

paths:
  /files:
    $ref: ingest/paths/files.yaml
  /folders:
    $ref: ingest/paths/folders.yaml
  /entries/{entryId}:
    $ref: ingest/paths/entries_{entryId}.yaml
  /entries/{entryId}/move:
    $ref: ingest/paths/entries_{entryId}_move.yaml
  /entries/{entryId}/metadata:
    $ref: ingest/paths/entries_{entryId}_metadata.yaml
